import test from "node:test";import assert from "node:assert/strict";import {createRequire} from "node:module";import {readFile} from "node:fs/promises";const require=createRequire(import.meta.url),{createCloseFlow,backupFilename}=require("../desktop/close-flow.cjs");
function harness(response,save={canceled:false,filePath:"/tmp/a.conta.json"},fail=false,locale="ar"){const calls=[],messageBoxes=[],saveDialogs=[];const flow=createCloseFlow({dialog:{showMessageBox:async(_window,options)=>{messageBoxes.push(options);return{response}},showSaveDialog:async(_window,options)=>{saveDialogs.push(options);return save}},window:()=>null,getLocale:async()=>locale,fetchBackup:async()=>{calls.push("backup");if(fail)throw Error("fail");return Buffer.from("data")},writeBackup:async()=>calls.push("write"),approveQuit:async()=>calls.push("quit"),onFailure:async()=>calls.push("failure")});return{flow,calls,messageBoxes,saveDialogs}}
test("YES saves before quit and cannot prompt twice",async()=>{const h=harness(0);assert.equal(await h.flow.requestClose(),true);assert.deepEqual(h.calls,["backup","write","quit"]);assert.equal(await h.flow.requestClose(),true);assert.deepEqual(h.calls,["backup","write","quit"])});
test("NO quits without backup",async()=>{const h=harness(1);assert.equal(await h.flow.requestClose(),true);assert.deepEqual(h.calls,["quit"])});
test("CANCEL and save cancellation keep app open",async()=>{let h=harness(2);assert.equal(await h.flow.requestClose(),false);assert.deepEqual(h.calls,[]);h=harness(0,{canceled:true});assert.equal(await h.flow.requestClose(),false);assert.deepEqual(h.calls,[])});
test("backup failure reports and does not quit",async()=>{const h=harness(0,undefined,true);assert.equal(await h.flow.requestClose(),false);assert.deepEqual(h.calls,["backup","failure"]);assert.equal(h.messageBoxes.length,2)});
test("French close and save dialogs follow the selected UI language",async()=>{let h=harness(2,undefined,false,"fr");assert.equal(await h.flow.requestClose(),false);assert.equal(h.messageBoxes[0].message,"Voulez-vous enregistrer une sauvegarde avant de quitter ?");assert.deepEqual(h.messageBoxes[0].buttons,["Oui, sauvegarder","Non, quitter","Annuler"]);h=harness(0,{canceled:true},false,"fr");await h.flow.requestClose();assert.equal(h.saveDialogs[0].title,"Enregistrer la sauvegarde");assert.equal(h.saveDialogs[0].filters[0].name,"Sauvegarde Al Karna Parfums")});
test("French backup failure stays localized",async()=>{const h=harness(0,undefined,true,"fr");assert.equal(await h.flow.requestClose(),false);assert.equal(h.messageBoxes[1].message,"Impossible de créer la sauvegarde. L’application reste ouverte.");assert.deepEqual(h.messageBoxes[1].buttons,["OK"])});
test("filename and desktop route security/source use native backup",async()=>{assert.match(backupFilename(new Date(2026,8,1,14,5)),/^AlKarna-Perfume-backup-2026-09-01-1405\.conta\.json$/);const route=await readFile(new URL("../app/api/desktop/backup/route.ts",import.meta.url),"utf8"),main=await readFile(new URL("../desktop/main.cjs",import.meta.url),"utf8");assert.match(route,/createNativeBackup\(await getDatabase\(\)\)/);assert.match(route,/timingSafeEqual/);assert.match(route,/ALKARNA_DESKTOP/);assert.match(main,/randomBytes\(32\)/);assert.match(main,/cookies\.get\(\{url:serverUrl,name:LOCALE_COOKIE\}\)/);assert.ok(main.indexOf('fetchBackup')<main.indexOf('approveQuit'))});
